---
all:
  children:
    nexus:
      vars:
        device_type: 5548  # 5548 or 93128
        # push_config: true  # false builds local configs, true pushs config
        ansible_connection: "local"
      hosts:
        sw1:
        sw2:
...
