---
- name: "Add MOTD banner on Nexus {{ device_type }} from motd_banner.txt"
  nxos_banner:
    banner: "motd"
    text: "{{ motd_banner }}"

- name: "Push configuration to Nexus {{ device_type }}"
  nxos_config:
    src: "{{ playbook_dir }}/templates/nexus{{ device_types }}.j2"
    save_when: "changed"
...
