---
- block:
    - name: "Get ansible date/time facts"
      setup:
        filter: "ansible_date_time"
        gather_subset: "!all"

    - name: "Store date/time group (DTG) as fact"
      set_fact:
        DTG: "{{ ansible_date_time.iso8601_basic_short }}"

    - name: "Create configs/ directory"
      file:
        path: "configs"
        state: "directory"

    - name: "Create date-specific subdirectory {{ DTG }}/"
      file:
        path: "configs/{{ DTG }}"
        state: "directory"
  run_once: true

- name: "Generate local config files"
  template:
    src: "templates/nexus{{ device_type }}.j2"
    dest: "configs/{{ DTG }}/{{ inventory_hostname }}.txt"
    # newline_sequence: "\r\n"
