---
- block:
    - name: "Ensure 'ansible_connection' is assigned a valid value"
      assert:
        that:
          - "ansible_connection is defined"
          - "ansible_connection in ['local', 'network_cli']"
        msg: "Invalid value for 'ansible_connection'; {{ ansible_connection }}"

    - name: "Ensure 'device_type' is assigned a valid value"
      assert:
        that:
          - "device_type is defined"
          - "device_type | int in [5548, 93128]"
        msg: "Invalid value for 'device_type'; {{ device_type }}"

    - name: "Set peer_hostname to 'a' on node 'b'"
      set_fact:
        peer_hostname: "a"
      when: "inventory_hostname == 'b'"

    - name: "Set peer_hostname to 'b' on node 'a'"
      set_fact:
        peer_hostname: "b"
      when: "inventory_hostname == 'a'"

    - name: "Store MOTD banner text"
      set_fact:
        motd_banner: "{{ lookup('file', playbook_dir ~ '/motd_banner.txt') }}"

  delegate_to: "localhost"
...
